execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=1}] run scoreboard players set @s mana 10 
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=2}] run scoreboard players set @s mana 50
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=3}] run scoreboard players set @s mana 100
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=4,mana=..24}] run scoreboard players set @s mana 25
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=4,mana=..399}] run scoreboard players add @s mana 100
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=4,mana=400..}] run scoreboard players set @s mana 500
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=5,mana=..49}] run scoreboard players set @s mana 50
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=5,mana=..899}] run scoreboard players add @s mana 100
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=5,mana=900..}] run scoreboard players set @s mana 1000
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=6,mana=..249}] run scoreboard players set @s mana 250
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=6,mana=..4899}] run scoreboard players add @s mana 100
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=6,mana=4900..}] run scoreboard players set @s mana 5000
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=7,mana=..499}] run scoreboard players set @s mana 500
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=7,mana=..9899}] run scoreboard players add @s mana 100
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=7,mana=9900..}] run scoreboard players set @s mana 10000
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=8,mana=..2499}] run scoreboard players set @s mana 2500
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=8,mana=..49899}] run scoreboard players add @s mana 100
execute as @a[tag=used_mana_potion_ii,scores={wizard_rank=8,mana=49900..}] run scoreboard players set @s mana 50000