execute as @s[scores={wizard_rank=1}] run scoreboard players set @s mana 10
execute as @s[scores={wizard_rank=2,mana=..39}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=2,mana=40..}] run scoreboard players set @s mana 50
execute as @s[scores={wizard_rank=3,mana=..0}] run scoreboard players set @s mana 1
execute as @s[scores={wizard_rank=3,mana=..89}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=3,mana=90..}] run scoreboard players set @s mana 100
execute as @s[scores={wizard_rank=4,mana=..4}] run scoreboard players set @s mana 5
execute as @s[scores={wizard_rank=4,mana=..489}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=4,mana=490..}] run scoreboard players set @s mana 500
execute as @s[scores={wizard_rank=5,mana=..9}] run scoreboard players set @s mana 10
execute as @s[scores={wizard_rank=5,mana=..989}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=5,mana=990..}] run scoreboard players set @s mana 1000
execute as @s[scores={wizard_rank=6,mana=..49}] run scoreboard players set @s mana 50
execute as @s[scores={wizard_rank=6,mana=..4989}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=6,mana=4990..}] run scoreboard players set @s mana 5000
execute as @s[scores={wizard_rank=7,mana=..99}] run scoreboard players set @s mana 100
execute as @s[scores={wizard_rank=7,mana=..9989}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=7,mana=9990..}] run scoreboard players set @s mana 10000
execute as @s[scores={wizard_rank=8,mana=..499}] run scoreboard players set @s mana 500
execute as @s[scores={wizard_rank=8,mana=..49989}] run scoreboard players add @s mana 10
execute as @s[scores={wizard_rank=8,mana=49990..}] run scoreboard players set @s mana 50000